name: admin_app
description: "Clinic admin appointment management app for health platform."
publish_to: 'none'
version: 1.0.0+1

resolution: workspace

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.2.1
  go_router: ^14.6.0
  intl: ^0.20.2
  api_sdk:
    path: ../../packages/dependencies

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
